
ESCOLAS = [
    ('18 De Outubro', '18 De Outubro'),
    ('Alegria Do Saber', 'Alegria Do Saber'),
    ('Ana Maria Machado', 'Ana Maria Machado'),
    ('Antonio Matos', 'Antonio Matos'),
    ('Antonio Vilhena', 'Antonio Vilhena'),
    ('Arco Iris', 'Arco Iris'),
    ('Benedito Monteiro', 'Benedito Monteiro'),
    ('Carlos Drummond', 'Carlos Drummond'),
    ('Carlos Henrique', 'Carlos Henrique'),
    ('Cecilia Meireles', 'Cecilia Meireles'),
    ('Chico Mendes', 'Chico Mendes'),
    ('Comecinho De Vida', 'Comecinho De Vida'),
    ('Cora Coralina', 'Cora Coralina'),
    ('Creche', 'Creche'),
    ('Crescendo Na Prática', 'Crescendo Na Prática'),
    ('Criança Esperança', 'Criança Esperança'),
    ('Deyse Lorena', 'Deyse Lorena'),
    ('Deyse Lorrena - Anexo', 'Deyse Lorrena - Anexo'),
    ('Domingos Cardoso', 'Domingos Cardoso'),
    ('Dona Rosa', 'Dona Rosa'),
    ('Doroth Stang', 'Doroth Stang'),
    ('Doroth Stang - Anexo', 'Doroth Stang - Anexo'),
    ('Eduardo Angelim', 'Eduardo Angelim'),
    ('Eduardo Angelim - Estado', 'Eduardo Angelim - Estado'),
    ('Elisaldo Ribeiro', 'Elisaldo Ribeiro'),
    ('Eunice Moreira', 'Eunice Moreira'),
    ('Eurides Santana', 'Eurides Santana'),
    ('Faruk Salmen', 'Faruk Salmen'),
    ('Fernando Pessoa', 'Fernando Pessoa'),
    ('Gente Inocente', 'Gente Inocente'),
    ('Gonçalves Dias', 'Gonçalves Dias'),
    ('Irmã Dulce', 'Irmã Dulce'),
    ('Irmã Laura', 'Irmã Laura'),
    ('Jean Piaget', 'Jean Piaget'),
    ('João Evangelista', 'João Evangelista'),
    ('João Prudencio', 'João Prudencio'),
    ('Jorge Amado', 'Jorge Amado'),
    ('Jozias Leão', 'Jozias Leão'),
    ('Leide Maria', 'Leide Maria'),
    ('Leide Maria - Anexo', 'Leide Maria - Anexo'),
    ('Luis Magno', 'Luis Magno'),
    ('Machado De Assis', 'Machado De Assis'),
    ('Maria Salete', 'Maria Salete'),
    ('Mario Lago', 'Mario Lago'),
    ('Mario Lago - Anexo', 'Mario Lago - Anexo'),
    ('Marluce Massariol', 'Marluce Massariol'),
    ('Milton Martins', 'Milton Martins'),
    ('Monteiro Lobato', 'Monteiro Lobato'),
    ('Monteiro Lobato - Z.Rural', 'Monteiro Lobato - Z.Rural'),
    ('Moranguinho', 'Moranguinho'),
    ('Mundo Infantil', 'Mundo Infantil'),
    ('Nelson Mandela', 'Nelson Mandela'),
    ('Novo Horizonte', 'Novo Horizonte'),
    ('Olga Da Silva', 'Olga Da Silva'),
    ('Oziel Pereira', 'Oziel Pereira'),
    ('Paulo Fonteles', 'Paulo Fonteles'),
    ('Paulo Freire', 'Paulo Freire'),
    ('Pequeno Principe', 'Pequeno Principe'),
    ('Pingo De Gente', 'Pingo De Gente'),
    ('Plácido De Castro', 'Plácido De Castro'),
    ('Primavera II', 'Primavera II'),
    ('Projeto Presença - Semas', 'Projeto Presença - Semas'),
    ('Ruth Rocha', 'Ruth Rocha'),
    ('Ruth Rocha - Anexo', 'Ruth Rocha - Anexo'),
    ('Sandra Maria', 'Sandra Maria'),
    ('Santa Tereza', 'Santa Tereza'),
    ('Sorriso De Criança', 'Sorriso De Criança'),
    ('Terezinha De Jesus', 'Terezinha De Jesus'),
    ('Terezinha De Jesus - Anexo', 'Terezinha De Jesus - Anexo'),
    ('Turma Da Mônica', 'Turma Da Mônica'),
    ('Vovó Ana', 'Vovó Ana'),
    ('Zilda Arns', 'Zilda Arns'),
]


ESCOLARIDADE = [
    ('Não se aplica', 'Não se aplica'),
    ('Nenhuma', 'Nenhuma'),
    ('Educação de Jovens e Adultos (EJA)', 'Educação de Jovens e Adultos (EJA)'),
    ('Educação infantil incompleta', 'Educação infantil incompleta'),
    ('Educação infantil completa', 'Educação infantil completa'),
    ('Fundamental incompleto', 'Fundamental incompleto'),
    ('Fundamental completo', 'Fundamental completo'),
    ('Médio incompleto', 'Médio incompleto'),
    ('Médio completo', 'Médio completo'),
    ('Superior incompleto', 'Superior incompleto'),
    ('Superior completo', 'Superior completo'),
    ('Especialização incompleto', 'Especialização incompleto'),
    ('Especialização completo', 'Especialização completo'),
    ('Mestrado incompleto', 'Mestrado incompleto'),
    ('Mestrado completo', 'Mestrado completo'),
    ('Doutorado incompleto', 'Doutorado incompleto'),
    ('Pós doutorado incompleto', 'Pós doutorado incompleto'),
    ('Pós doutorado completo', 'Pós doutorado completo'),
]
