# Generated by Django 3.2.11 on 2022-06-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_cid_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='nome_secretaria',
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.ImageField(blank=True, null=True, upload_to='pessoa_documento/'),
        ),
    ]
