# Generated by Django 3.2.11 on 2022-06-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220629_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cid',
            name='cid',
            field=models.CharField(max_length=255),
        ),
    ]
